### PR TITLE
Add 'RisingTechOSS' in README

### PR DESCRIPTION
**Pull request by ThatMalayaliDeb**

### CODE REVIEW

**Comment by FPSensor** [comment]
will be good if u also remove RiceDroid obsolete one

**Comment by ThatMalayaliDeb** [comment]
left it as it is if anyone wants to revive it later.

**Comment by FPSensor** [comment]
It's better to drop cuz ricedroid org doesn't exist now

**Comment by ThatMalayaliDeb** [comment]
lets see if he merge this PR xD if he does i have another rom to add in the list, with that i will remove ricedroid then.... :D

**Comment by FPSensor** [comment]
Cool, let's see

**Pull request merged**
